api_key: ''
response_limit: 50000
symbols: ['AAPL', 'MSFT']
dates: ['2019-01-02', '2019-01-03']
time_zone: 'US/Eastern'
max_start_hour: 9
max_start_minute: 35
min_end_hour: 15
min_end_minute: 55
max_delta_minutes: 5

# Comment out the filename lines to skip writing the respective files.
download_path: 'data'
quotes_responses_filename: 'quotes.responses.gz'
quotes_csv_filename: 'quotes.csv.gz'
trades_responses_filename: 'trades.responses.gz'
trades_csv_filename: 'trades.csv.gz'

# Passed through to logging.config.dictConfig(config).
logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s %(levelname)-8s %(name)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: DEBUG
    handlers: [console]