lambda_function: features_day
s3_bucket: reup
# s3_key_input_prefix: historical-data/time-series/
s3_key_input_prefix: scratch/historical-data/time-series/
s3_key_input_suffix: time-series.csv.gz
# s3_key_output_prefix: features/day/
s3_key_output_prefix: scratch/features/day/
s3_key_output_suffix: features.csv.gz
max_event_count: 600
sleep_seconds: 30
